import React from "react";
import Head from "next/head";
import Image from "next/legacy/image";

import Navy from "../assets/navy-logo.png";
import DNED from "../assets/dned.png";
import { PastDirectors } from "../components/utils/pastdirectors/pastDirectors";

const About = () => {
  return (
    <div className="bg-pagesbg">
      <Head>
        <title>NNEDU | The Directorate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full items-center justify-center">
        <div className="w-full max-w-[1440px]">
          <div className="p-4 bg-accent flex justify-center h-[28rem] items-center">
            <div className="w-full max-w-[70rem] p-4 flex flex-col gap-y-6 justify-center items-center">
              <Image src={Navy} alt="navy" />
              <h2
                className="font-inter text-2xl md:text-3xl font-bold tracking-[0.06em] 
                text-center capitalize leading-8 text-white"
              >
                About
              </h2>
            </div>
          </div>
        </div>

        <div className="md:-mt-24 md:mb-14 h-auto px-6 md:px-12 py-12 w-full max-w-[50rem] bg-white">
          <div className="flex flex-col gap-4">
            <h2
              className="font-inter text-2xl font-bold tracking-[0.06em] 
                text-center capitalize leading-8 text-primary"
            >
              the directorate
            </h2>
            <p className="text-base font-montserrat tracking-[0.06em] font-normal text-center leading-7">
              The Directorate of Naval Education is one of the Directorates
              under the Administration Branch and is headed by an Officer of
              <b> Commodore rank</b>. The Directorate has both primary and
              secondary roles. The primary role of the Directorate is in
              training support while its secondary role is in welfare support.
              In the training support role, it develops the academic and
              intellectual endowments of naval personnel in support of naval
              operations. This is done through training in professional schools
              and Bases/Units In the welfare support role, the Directorate runs
              the NN Primary and Secondary schools on behalf of the{" "}
              <b>Chief of the Naval staff (CNS)</b>. The Directorate of Naval
              Education also maintains the Inspectorate and Education Research
              Division to ensure that all school standards and educational
              programmes are harmonized and monitored. The{" "}
              <b>Directorate of Naval Education</b> provides policy guidelines
              for NN primary, secondary and professional schools and advisory
              roles to NOWA schools.
            </p>
          </div>
        </div>

        <div className="w-full max-w-[1440px]">
          <div className="p-4 bg-white border-secondary border-t-8 flex justify-center items-center">
            <div className="w-full max-w-[70rem] p-4 grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-4 flex items-center gap-4 flex-col justify-center w-full">
                <h2
                  className="font-inter text-2xl md:text-3xl font-bold tracking-[0.06em] 
                text-left capitalize w-full leading-8 text-primary"
                >
                  The Director
                </h2>
                <p className="text-base w-full font-montserrat tracking-[0.06em] font-normal text-left leading-7">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do t tempor incididunt ut labore et dolore magna aliqua. Ut
                  enim ad minim veniam, quis nostrud exer
                </p>
              </div>
              <div className="p-4 flex items-center justify-center">
                <Image
                  src={DNED}
                  alt="cns"
                  priority={100}
                  width={305}
                  height={423}
                  layout="intrinsic"
                />
              </div>
            </div>
          </div>
        </div>

        <div className="w-full max-w-[1440px]">
          <div className="flex p-4 items-center justify-center h-auto md:h-[58rem]">
            <div className="w-full p-4 max-w-[70rem] flex flex-col">
              <h2
                className="font-inter text-2xl md:text-3xl font-bold tracking-[0.06em] 
                text-center md:text-left capitalize leading-8 text-primary"
                id="#pastdirectors"
              >
                Past Directors
              </h2>
              <div className="w-full my-10">
                <PastDirectors />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
