import React from 'react'
import Head from "next/head";

const About = () => {
  return (
    <div>
        <Head>
        <title>NNEDU | The Directorate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>hello about the directorate</div>
    </div>
  )
}

export default About