import React from "react";
import { client } from "../lib/apollo";
import { gql } from "@apollo/client";
import { UiBlog } from "../components/utils/blogpost/uiblog";
import Head from "next/head";

export default function Blog({ posts }) {
  return (
    <div>
      <Head>
        <title>NNEDU | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center w-full">
        <div className="w-full max-w-[1440px]">
          <div className="flex w-full justify-center items-center bg-secondary h-[28rem]">
            <div className="p-4 w-full max-w-[70rem] flex items-center justify-center">
              <h2
                className="font-inter text-2xl md:text-3xl font-black tracking-[0.06em] 
                text-center capitalize leading-8 text-primary"
              >
                DNED Blog
              </h2>
            </div>
          </div>
        </div>

        {/* <div className="w-full max-w-[1440px]">
          <div className="flex w-full items-center justify-center bg-white h-auto py-10 px-6">
            <div className="w-full max-w-[70rem] grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {posts.map((post) => {
                return <UiBlog key={post.uri} post={post} />;
              })}
            </div>
          </div>
        </div> */}

      </div>
    </div>
  );
}

// export async function getStaticProps() {
//   const GET_POSTS = gql`
//     query GetAllPosts {
//       posts {
//         nodes {
//           title
//           uri
//           date
//           excerpt
//           featuredImage {
//             node {
//               id
//               sourceUrl
//               srcSet
//             }
//           }
//         }
//       }
//     }
//   `;

//   const res = await client.query({
//     query: GET_POSTS,
//   });
//   console.log(res);

//   const posts = res?.data?.posts?.nodes;
//   console.log(posts);
//   return {
//     props: {
//       posts,
//     },
//   };
// }
