import React from "react";
import Head from "next/head";
import Image from "next/legacy/image";

const Contact = () => {
  return (
    <div className="bg-accent">
      <Head>
        <title>NNEDU | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div></div>
    </div>
  );
};

export default Contact;
