import React from "react";
import Head from "next/head";
import MapNNEDU from "../components/utils/map/map";
import { SocialMedia } from "../components/utils/socials/social";

const Contact = () => {
  return (
    <div className="bg-white">
      <Head>
        <title>NNEDU | Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full items-center justify-center">
        {/* map component */}
        <div>
          <MapNNEDU />
        </div>
        <div className="w-full max-w-[1440px] z-50">
          <div className="bg-primary p-4 h-20 flex justify-center items-center">
            <div className="w-full flex items-center justify-between max-w-[70rem]">
              <SocialMedia />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Contact;
