import { Icon } from "@iconify/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { SchoolTabs } from "../components/utils/schooltabs/schooltabs";

const School = () => {
  return (
    <div className="bg-pagesbg">
      <Head>
        <title>NNEDU | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full items-center justify-center">
        <div className="w-full max-w-[1440px]">
          <div className="bg-secondary px-6 w-full flex h-[28rem] justify-center items-center">
            <div className="w-full max-w-[70rem] flex gap-4 justify-center flex-col">
              <h2 className="w-full text-left text-primary font-inter tracking-[0.06em] text-2xl md:text-3xl font-bold">
                DNED Establishment
              </h2>
              <p className="w-full text-left max-w-xl text-primary font-montserrat tracking-[0.06em] font-medium">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                t tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
                minim veniam, quis nostrud exer
              </p>
              <div className="">
                <Link href="#" passHref legacyBehavior>
                  <a className="text-primary hover:text-accent active:text-accent">
                    <Icon
                      icon="iconoir:mouse-scroll-wheel"
                      width="28"
                      height="28"
                    />
                  </a>
                </Link>
              </div>
            </div>
          </div>
        </div>

        <div className="w-full max-w-[1440px]">
          <div className="bg-white px-6 py-10 w-full flex justify-center items-center">
            <div className="w-full max-w-[70rem]">
              <SchoolTabs />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default School;
